### ISSUE TITLE
Android 11 下检测是否安装微信失败

### ISSUE THREAD

**Issue by zhxst** [RxReader/wechat_kit#138]
在Android 11 下，调用`WechatKitPlatform.instance.isInstalled()`始终返回false。
在iOS下就正常。

在网上及微信平台搜索，都说需要在AndroidManifest.xml中，加入以下字段
```xml
<queries>
   //微信包名
    <package android:name="com.tencent.mm" />
</queries>
```
我在我的App中加入了也没有效果，但是我看plugin的`android/src/vendor/AndroidManifest.xml`下是有加这个的。
是还需要什么额外的配置吗？

**Comment by MrBMask** [comment]
我也是同样的问题在安卓设备上

**Comment by darkdong** [comment]
必须先调用`WechatKitPlatform.instance.registerApp`

**Comment by zhxst** [comment]
> 必须先调用`WechatKitPlatform.instance.registerApp`

确实
