### ISSUE TITLE
说未指定namespace。 我指定了啊 

### ISSUE THREAD

**Issue by zjm1126** [RxReader/wechat_kit#139]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':wechat_kit'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

     If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

在Android->app->build.gradle.  已经指定了。 AndroidManifest.xml 的package 也添加了   AGP也更新了。还是没用

**Comment by IoTServ** [comment]
这个插件要更新，插件添加这个namespace
