### ISSUE TITLE
腾讯开放平台上架提示我要先同意隐私协议在初始化插件，目前我已经做了，审核员还让我重新搞

### ISSUE THREAD

**Issue by Jackfinal** [RxReader/wechat_kit#140]
`void init (context){
    WechatKitPlatform.instance.registerApp(
      appId: kWechatAppID,
      universalLink: kWechatUniversalLink,
    );
  }`

这个代码是在 用户点击同意后，才去执行

审核员调取的
以下是堆栈信息：
`{
  "date": "2024-01-31 11:04:04.907",
  "action": "获取已安装APP信息",
  "data": {
    "packageName": "com.tencent.mm",
    "flag": 64
  },
  "stack": "android.app.ApplicationPackageManager.getPackageInfoAsUser(java.lang.String,int,int)\nandroid.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:152)\ncom.tencent.mm.opensdk.openapi.WXApiImplComm.validateAppSignatureForPackage(Unknown Source:20)\ncom.tencent.mm.opensdk.openapi.BaseWXApiImplV10.registerApp(Unknown Source:10)\ncom.tencent.mm.opensdk.openapi.BaseWXApiImplV10.registerApp(Unknown Source:2)\np4.a.x(Unknown Source:16)\np4.a.f(Unknown Source:10)\ng4.k$a.a(Unknown Source:17)\nt3.c.l(Unknown Source:18)\nt3.c.m(Unknown Source:40)\nt3.c.i(Unknown Source:0)\nt3.b.run(Unknown Source:12)\nandroid.os.Handler.handleCallback(Handler.java:873)\njava.lang.reflect.Method.invoke(Native Method)\n"
}`

![ffb8ec66ec1e4922cb0c0c2c701718c5](https://github.com/RxReader/wechat_kit/assets/15246879/3f3deae5-3dd2-4893-adb9-5f8ec3ef3297)

麻烦帮忙看一下，怎么才能让用户同意后才去初始化 插件

**Comment by lwj1994** [comment]
you can use https://github.com/lwj1994/privacy_hook to hook android get-package api
