### ISSUE TITLE
微信分享不管成功分享或者取消分享，Stream监听的结果都是0,null

### ISSUE THREAD

**Issue by wwtsu** [RxReader/wechat_kit#20]
请问我能知道使用者是否成功分享出去了吗？

**Comment by v7lin** [comment]
iOS可以。Android以前可以，现在不行了，微信不论是分享成功或者失败均是返回0，当然可以判断是否为取消分享。

**Comment by CodeGather** [comment]
这是微信的问题，android的取消了是否分享成功

**Comment by situxinxin** [comment]
亲...我这面微信回调都不走 能请教一下么?
