### ISSUE TITLE
启动时 提示 No known class method for selector 'registerApp:enableMTA:'

### ISSUE THREAD

**Issue by tom0gao** [RxReader/wechat_kit#21]
是我什么地方导入不对吗？
No known class method for selector 'registerApp:enableMTA:'
No known class method for selector 'sendReq:'

**Comment by v7lin** [comment]
podfile.lock 里的 WechatOpenSDK 版本是多少？

**Comment by tom0gao** [comment]
- fake_wechat (0.0.1):
  - Flutter
  - WechatOpenSDK (~&gt; 1.8.4)




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "林恒龙"<notifications@github.com&gt;; 
发送时间: 2019年10月30日(星期三) 下午5:09
收件人: "v7lin/fake_wechat"<fake_wechat@noreply.github.com&gt;; 
抄送: "猜猜我是谁"<tom0gao@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [v7lin/fake_wechat] 启动时 提示 No known class method for selector &#39;registerApp:enableMTA:&#39; (#21)




podfile.lock 里的 WechatOpenSDK 版本是多少？

**Comment by v7lin** [comment]
先用 git 方式引入工程

**Comment by tom0gao** [comment]
@v7lin  OK

**Comment by tom0gao** [comment]
@v7lin 
ios运行过程中 微信sdk还是有异常
->  0x104b97f94 <+96>:   cbz    x0, 0x104b980f8           ; <+452> at WXApi.m:41:9 
2019-10-30 17:38:26.130088+0800 Runner[4374:832655] -[NSNull length]: unrecognized selector sent to instance 0x1c87239a0

**Comment by crazySadSoul** [comment]
> 是我什么地方导入不对吗？
> No known class method for selector 'registerApp:enableMTA:'
> No known class method for selector 'sendReq:'

你解决了吗，我也是同样的报错。
