### ISSUE TITLE
IOS 0.3.4 升级到 1.0.1 之后微信登录无回调

### ISSUE THREAD

**Issue by StimeKe** [RxReader/wechat_kit#31]
IOS 0.3.4 升级到 1.0.1 之后微信登录无回调

大佬这是啥问题 0.3.4 没有任何问题

**Comment by v7lin** [comment]
请配置 Universal Link

**Comment by StimeKe** [comment]
@v7lin 0.3.4也需要配置 Universal Link ，都已经配置完成，0.3.4可以正常使用。

**Comment by StimeKe** [comment]
@v7lin 我这边根据微信IOS入门指南进行配置，1.0.1可以成功唤起微信，并且未出现二次确认，表示 Universal Link 正常，但是无回调。

**Comment by v7lin** [comment]
😳 还有这事儿？1.0.1和0.3.4几乎没差别。那先用0.3.4吧 … 我最近再抽空看看 …

**Comment by Xiaojuanmao** [comment]
大佬求修复，我用的是1.0.2版本，Android可以正常登录，ios这边没有回调，我确定我的universal link也是正确的。刚开始以为是我的使用姿势错了，直到看了这个issue
