### ISSUE TITLE
升级到1.1.0 之后无法获取登录回调，无法分享，UniversalLink配置正常

### ISSUE THREAD

**Issue by Airoyee** [RxReader/wechat_kit#42]
期待大佬回复

**Comment by v7lin** [comment]
有demo工程吗？还有附上demo工程需要的签名

**Comment by Airoyee** [comment]
> 有demo工程吗？还有附上demo工程需要的签名

没写demo工程，之前用的0.3.0版本，ios端没有配置UniversalLink，但是可以正常分享登录。升级到新版本后配置完UniversalLink，可以唤起微信，但是返回app后不走回调。

感谢大佬回复

**Comment by v7lin** [comment]
明天修正一下

**Comment by v7lin** [comment]
项目中是否用了SceneDelegate？

**Comment by Airoyee** [comment]
> 项目中是否用了SceneDelegate？

全局搜索了一下，没有使用SceneDelegate😂，我是做Android开发的，iOS储备基本为0😂

**Comment by v7lin** [comment]
巧了，我也是 Android 的，会点 iOS

**Comment by Airoyee** [comment]
> 巧了，我也是 Android 的，会点 iOS

摩拜大佬啊，我都让oc愁哭了

**Comment by v7lin** [comment]
目前手头上没有 iOS 的项目，没法调试 universalLink，我也挺惆怅的 ... 你要不创建个Demo（或只直接fork一份项目），然后把Demo改成自己项目的配置，并把我加到iOS开发者成员里去，我好调试问题？
