### ISSUE TITLE
flutter pub get完后，直接运行项目报错了

### ISSUE THREAD

**Issue by MrNew** [RxReader/wechat_kit#43]
<img width="660" alt="截屏2020-07-06下午9 19 22" src="https://user-images.githubusercontent.com/19178674/86597676-a0ca4480-bfce-11ea-8795-8a8d95df36ed.png">

wechat_kit: ^1.1.0 安装的是这个版本的

**Comment by MrNew** [comment]
Undefined symbols for architecture arm64:
  "operator new[](unsigned long)", referenced from:
      +[WeChatApiUtil EncodeBase64:] in libWeChatSDK.a(WeChatApiUtil.o)
      +[WeChatApiUtil NsDataEncodeBase64:] in libWeChatSDK.a(WeChatApiUtil.o)
      +[WeChatApiUtil DecodeWithBase64:] in libWeChatSDK.a(WeChatApiUtil.o)
      +[WeChatApiUtil DecodeBase64:] in libWeChatSDK.a(WeChatApiUtil.o)
  "___cxa_begin_catch", referenced from:
      ___clang_call_terminate in libWeChatSDK.a(WechatAuthSDK.o)
  "operator delete[](void*)", referenced from:
      +[WeChatApiUtil EncodeBase64:] in libWeChatSDK.a(WeChatApiUtil.o)
      +[WeChatApiUtil NsDataEncodeBase64:] in libWeChatSDK.a(WeChatApiUtil.o)
      +[WeChatApiUtil DecodeWithBase64:] in libWeChatSDK.a(WeChatApiUtil.o)
      +[WeChatApiUtil DecodeBase64:] in libWeChatSDK.a(WeChatApiUtil.o)
  "std::terminate()", referenced from:
      ___clang_call_terminate in libWeChatSDK.a(WechatAuthSDK.o)
  "___gxx_personality_v0", referenced from:
      -[WechatAuthSDK init] in libWeChatSDK.a(WechatAuthSDK.o)
      -[WechatAuthSDK dealloc] in libWeChatSDK.a(WechatAuthSDK.o)
      -[WechatAuthSDK resetAll] in libWeChatSDK.a(WechatAuthSDK.o)
      -[WechatAuthSDK resetConnection] in libWeChatSDK.a(WechatAuthSDK.o)
      -[WechatAuthSDK Auth:nonceStr:timeStamp:scope:signature:schemeData:] in libWeChatSDK.a(WechatAuthSDK.o)
      -[WechatAuthSDK StopAuth] in libWeChatSDK.a(WechatAuthSDK.o)
      -[WechatAuthSDK sendAuthRequest:] in libWeChatSDK.a(WechatAuthSDK.o)
      ...
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by MrNew** [comment]
解决方法：在Xocde中导入libc++.tbd

**Comment by v7lin** [comment]
@MrNew 稍后我在项目中集成一下
