### ISSUE TITLE
更新到1.1.0版本后，微信支付完成后无法获得回调

### ISSUE THREAD

**Issue by sec7et** [RxReader/wechat_kit#45]
此前使用旧版本，0.3.4，直接连接真机调试，微信支付完成后可以获得回调。但是iOS和Android打包之后均无法进入回调。
后更新到1.1.0版本，真机调试也无法进入回调了。现在很惆怅，麻烦作者老哥帮忙看一下。

```
  StreamSubscription<WechatPayResp> _pay;

  Wechat _wechat = Wechat()
    ..registerApp(
      appId: WECHAT_APPID,
      universalLink: WECHAT_UNIVERSAL_LINK,
    );

  @override
  void initState() {
    super.initState();
    _pay = _wechat.payResp().listen(_listenPay);
  }

  void _listenPay(WechatPayResp resp) {
    // 无法进入这里的回调
    showToast("正在查询支付结果");
    if (resp.errorCode == 0) {
      _checkPayResult();
    } else {
      showToast('支付失败');
    }
  }

  @override
  void dispose() {
    _pay?.cancel();
    super.dispose();
  }
```

这里的Flutter版本虽然显示unknown，但当初确实是从官网下载的stable版本。
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.12.13+hotfix.8, on Mac OS X 10.15.5 19F101,
    locale zh-Hans-CN)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.46.1)
[!] Proxy Configuration
    ! NO_PROXY is not set
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

**Comment by v7lin** [comment]
Demo呢？

**Comment by MrNew** [comment]
你调用部分的代码没有呀，看不全

**Comment by sec7et** [comment]
> 你调用部分的代码没有呀，看不全

调用部分的代码就是按照案例里面写的，调用api，就没贴了。。

**Comment by v7lin** [comment]
我直接连项目调试的，可以正常回调 … 将你的工程配置到example里跑一遍吧

**Comment by sec7et** [comment]
> 我直接连项目调试的，可以正常回调 … 将你的工程配置到example里跑一遍吧

嘶，我再检查一下。我觉得SDK应该是没什么问题的。。

**Comment by JiangJuHong** [comment]
我也遇到了这个问题  请问解决了吗。

````
设备： iPhone11 IOS 13.5.1
通用连接已经正常配置
````

登录：  不调用回调
分享：  显示正在连接后返回了APP，未打开微信。

**Comment by sec7et** [comment]
> 我也遇到了这个问题 请问解决了吗。
> 
> ```
> 设备： iPhone11 IOS 13.5.1
> 通用连接已经正常配置
> ```
> 
> 登录： 不调用回调
> 分享： 显示正在连接后返回了APP，未打开微信。

一样的情况，实在很无奈了。项目里其实集成了tencent_kit   weibo_kit，只有wechat_kit出了这问题。后来只能把这个换了另一个库了。

**Comment by JiangJuHong** [comment]
换成另一个库就没有这个问题了吗？请问是哪个库呢？ @sec7et

**Comment by sec7et** [comment]
> 换成另一个库就没有这个问题了吗？请问是哪个库呢？ @sec7et

fluwx 后来改用这个了

**Comment by JiangJuHong** [comment]
我在这个网站找到了一种答案，但是不确定是否是我们当前所遇到的这个问题。
https://developers.weixin.qq.com/community/develop/doc/00046e056ac8401a6559159bc51c00
如果是的话，可能需要麻烦作者修改一下 @v7lin

**Comment by JiangJuHong** [comment]
![image](https://user-images.githubusercontent.com/17740963/88279674-0df01080-cd17-11ea-87f3-0ddd16aab493.png)

**Comment by sec7et** [comment]
> 我在这个网站找到了一种答案，但是不确定是否是我们当前所遇到的这个问题。
> https://developers.weixin.qq.com/community/develop/doc/00046e056ac8401a6559159bc51c00
> 如果是的话，可能需要麻烦作者修改一下 @v7lin

这个很奇怪的地方是，直接用example里面的代码，配置成自己项目所需的环境，是走得通的。。

**Comment by JiangJuHong** [comment]
这样啊，那就有点麻烦了

**Comment by JiangJuHong** [comment]
只有先换成 fluwx 试试了

**Comment by v7lin** [comment]
升级 sdk 没配置 <string>weixinULAPI</string> 这个吧？

**Comment by sec7et** [comment]
> 升级 sdk 没配置下面这个吧？
> 
> ```
> <string>weixinULAPI</string>
> ```

是指在Info.plist文件下配置LSApplicationQueriesSchemes这个字段吗？

**Comment by v7lin** [comment]
嗯
