### ISSUE TITLE
很奇怪的分享动作，显示跳转到一个正在连接的一个页面 ，然后跳转到自己的App，最后跳转到微信的App，其它的像微博是直接跳转过去，这是什么情况

### ISSUE THREAD

**Issue by JamesBondPc** [RxReader/wechat_kit#47]

**Comment by CauliflowerGoer** [comment]
我也遇过了,  安卓直接过去,  IOS 会反复来两次

**Comment by situxinxin** [comment]
请问遇到解决办法了么?  还有一个问题,您的微信分享的回调 走了么?

**Comment by cavanlee** [comment]
连续发起分享，确认不会发生多次二次跳转行为
当用户首次使用新版本SDK发起分享时，将会出现如下交互流程：从App拉起微信-出现“正在连接”页面-返回App-重新打开微信。以上是新的安全验证流程，每个用户在首次使用时会出现上述跳转。（如同一用户多次使用分享都出现跳转，请按照以下接入指引，检查Universal Links配置）
[https://developers.weixin.qq.com/doc/oplatform/Mobile_App/Access_Guide/iOS.html](url)
