### ISSUE TITLE
iOS 微信分享提示 未验证应用

### ISSUE THREAD

**Issue by pdsliuzhen** [RxReader/wechat_kit#62]

**Comment by situxinxin** [comment]
亲,有修改成功么?  能请教一下怎么做的么?

**Comment by pdsliuzhen** [comment]
还没有，通用链接，我在验证下 看是不是他的事儿2021年1月12日 上午9:43，situxinxin <notifications@github.com> 写道：亲,有修改成功么?  能请教一下怎么做的么?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by situxinxin** [comment]
> 还没有，通用链接，我在验证下看是不是他的事儿2021年1月12日上午9：43，situxinxin <notifications@github.com>替代：亲戚，有修改成功么？能请教一下怎么做的么？？ —因为创建了线程，所以您收到此消息。直接回复此电子邮件，在GitHub上查看或取消订阅。

嗯嗯 好的   我现在这面就很无奈 微信分享成功 没有回调  然后还提示未验证...
