### ISSUE TITLE
不支持Android 11呀

### ISSUE THREAD

**Issue by wuyugege** [rxreader/wechat_kit#65]
content provider 方式分享图片不支持

**Comment by v7lin** [comment]
下个版本加吧

**Comment by wuyugege** [comment]
啥时候呀，其实我试了自己弄，不过失败了，你可以看一下这是啥问题
![image](https://user-images.githubusercontent.com/11754341/106345243-bd6ef680-62e9-11eb-93ea-0e2c74f21bcd.png)


> 下个版本加吧

**Comment by v7lin** [comment]
```yaml
dependencies:
  wechat_kit: ^2.0.0
```

```yaml
dependencies:
  wechat_kit: ^2.0.0-iOS-NoPay
```
