### ISSUE TITLE
在IOS里面，当未安装微信时，授权微信登录应该跳转到web上登录，但我这里点击微信登录时会出现错误

### ISSUE THREAD

**Issue by iboohii** [rxreader/wechat_kit#66]
您好，我这里点击微信登录时，会出现这个错误：
Could not signal service com.apple.WebKit.Networking: 113: Could not find specified service

failed for URL: "weixinULAPI://" - error: "未能完成操作。（OSStatus错误-10814。）"

**Comment by iboohii** [comment]
![](https://img-cdn-tc.dcloud.net.cn/uploads/questions/20180427/a90f367ca2a635a6d955f4667598bc6e.PNG)

**Comment by iboohii** [comment]
应该出现上面这个页面。

**Comment by v7lin** [comment]
微信iOS SDK不支持Web授权登录吧 ... 你可以尝试，先判断微信是否已安装，未安装时候使用微信扫描登录。

**Comment by iboohii** [comment]
我试了一下别的app,是可以web授权登录的呀。

**Comment by v7lin** [comment]
你来错地方了，你应该去接微信H5授权登录
