### ISSUE TITLE
请问什么时候能支持 wx-open-launch-app 唤起App

### ISSUE THREAD

**Issue by zfha** [RxReader/wechat_kit#68]

**Comment by tuchengdong** [comment]
其实 我也想问这个问题

**Comment by v7lin** [comment]
@zfha @tuchengdong 不知道这是啥玩意儿，有木有文档？

**Comment by a475893401** [comment]
> @zfha @tuchengdong 不知道这是啥玩意儿，有木有文档？

https://developers.weixin.qq.com/doc/offiaccount/OA_Web_Apps/Wechat_Open_Tag.html#跳转APP：wx-open-launch-app

**Comment by v7lin** [comment]
@a475893401 @zfha @tuchengdong 
最新的 3.0.0 （还木有发布，暂时先用 git 方式引入）已经支持微信回调请求了，不过木有验证条件，你们可以尝试一下

**Comment by tuchengdong** [comment]
好的好的~谢谢啊~辛苦了~其实 我也下载了你们的代码 改了一波 放在本地插件 用了一段时间了~哈哈哈~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RxReader/wechat_kit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月31日(星期六) 下午2:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RxReader/wechat_kit] 请问什么时候能支持 wx-open-launch-app 唤起App (#68)





 
@a475893401 @zfha @tuchengdong
 最新的 3.0.0 （还木有发布，暂时先用 git 方式引入）已经支持微信回调请求了，不过木有验证条件，你们可以尝试一下
