### ISSUE TITLE
安卓 shareEmoji 分享到微信卡片上显示 [应用消息]null，并且微信会卡住，在iOS下没有问题

### ISSUE THREAD

**Issue by xiangzy1** [rxreader/wechat_kit#69]
`_wechat.shareEmoji(
    scene: WechatScene.SESSION,
    thumbData: thumbData,
    emojiUri: Uri.file(filePath),
  );`
确定filePath有图片，调用保存图片可以正常在相册显示

**Comment by xiangzy1** [comment]
是 FileProvider 有问题吗

**Comment by v7lin** [comment]
> 是 FileProvider 有问题吗
请贴上你的版本信息，pubspec.lock里的

**Comment by xiangzy1** [comment]
我研究了一下，代码看起来没问题（安卓我不是很懂，打了几个Log看了眼都没错），是系统微信分身会导致失败，选择不分身的那个就行，这个大佬有空再看看吧

**Comment by v7lin** [comment]
@xiangzy1 这个爱莫能助了
