### ISSUE TITLE
请问有计划支持nullsafety吗？

### ISSUE THREAD

**Issue by shawnclovie** [rxreader/wechat_kit#70]
如题

**Comment by v7lin** [comment]
周末更新一个版本，或者你要是感兴趣，可以提交一个PR

**Comment by v7lin** [comment]
就等下周 build_runner 发布 nullsafety 了

**Comment by Sulisong** [comment]
期待合并！

**Comment by Sulisong** [comment]
期待nullsafety版本！

**Comment by v7lin** [comment]
@Sulisong 别急，排队中了 https://pub.dev/publishers/rxreader.com/packages

**Comment by Sulisong** [comment]
> @Sulisong 别急，排队中了 https://pub.dev/publishers/rxreader.com/packages

太棒了，期待效果，第一次使用。
