### ISSUE TITLE
插件2.3.0在ios14 无法执行回调函数

### ISSUE THREAD

**Issue by chen-tq** [rxreader/wechat_kit#76]
问题如题，我的环境是：
flutter: 2.0.4
dart: 2.12.2
xcode: 12
ios: 14
wechat_kit: 2.3.0

我使用flutter创建工程，使用插件2.3.0做微信登录功能。在安卓端能达到正确的效果，但在ios端，弹出微信授权页面，点击了“同意”后，跳回原app，但没有执行回调函数。

使用微信SDK自带的自检功能，检测到第4步就结束了，总共有7步。

情作者帮我看看是什么问题？

**Comment by v7lin** [comment]
请正确配置「Universal Links」

**Comment by chen-tq** [comment]
universal links 配置正确的。
我换了另一个插件 fluwx，就能成功。


我简单比对了2个程序，发现您的插件里，onReq 方法没有代码，但fluwx里有，我猜测问题可能出现在这。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rxreader/wechat_kit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月22日(星期四) 下午4:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rxreader/wechat_kit] 插件2.3.0在ios14 无法执行回调函数 (#76)





 
请正确配置「Universal Links」

**Comment by v7lin** [comment]
> universal links 配置正确的。 我换了另一个插件 fluwx，就能成功。 我简单比对了2个程序，发现您的插件里，onReq 方法没有代码，但fluwx里有，我猜测问题可能出现在这。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "rxreader/wechat_kit" ***@***.***&gt;; 发送时间:&nbsp;2021年4月22日(星期四) 下午4:50 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [rxreader/wechat_kit] 插件2.3.0在ios14 无法执行回调函数 (#76) 请正确配置「Universal Links」 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你查看一下你依赖的插件或者修改的工程有没有无差别拦截微信的 「Universal Links」回调（比如：app_links）。

**Comment by v7lin** [comment]
#48 #54
