### ISSUE TITLE
分享小程序失败

### ISSUE THREAD

**Issue by gitFreeByte** [rxreader/wechat_kit#77]
E/MethodChannel#v7lin.github.io/wechat_kit(17926): Failed to handle method call
E/MethodChannel#v7lin.github.io/wechat_kit(17926): java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.Integer
E/MethodChannel#v7lin.github.io/wechat_kit(17926): 	at io.github.v7lin.wechat_kit.WechatKitPlugin.handleShareMediaCall(WechatKitPlugin.java:482)
E/MethodChannel#v7lin.github.io/wechat_kit(17926): 	at io.github.v7lin.wechat_kit.WechatKitPlugin.onMethodCall(WechatKitPlugin.java:313)
E/MethodChannel#v7lin.github.io/wechat_kit(17926): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#v7lin.github.io/wechat_kit(17926): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#v7lin.github.io/wechat_kit(17926): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#v7lin.github.io/wechat_kit(17926): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#v7lin.github.io/wechat_kit(17926): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#v7lin.github.io/wechat_kit(17926): 	at android.os.Looper.loop(Looper.java:177)
E/MethodChannel#v7lin.github.io/wechat_kit(17926): 	at android.app.ActivityThread.main(ActivityThread.java:7993)
E/MethodChannel#v7lin.github.io/wechat_kit(17926): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#v7lin.github.io/wechat_kit(17926): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
E/MethodChannel#v7lin.github.io/wechat_kit(17926): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955)
E/flutter (17926): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(error, java.lang.Boolean cannot be cast to java.lang.Integer, null, java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.Integer
E/flutter (17926): 	at io.github.v7lin.wechat_kit.WechatKitPlugin.handleShareMediaCall(WechatKitPlugin.java:482)
E/flutter (17926): 	at io.github.v7lin.wechat_kit.WechatKitPlugin.onMethodCall(WechatKitPlugin.java:313)
E/flutter (17926): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (17926): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (17926): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/flutter (17926): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (17926): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/flutter (17926): 	at android.os.Looper.loop(Looper.java:177)
E/flutter (17926): 	at android.app.ActivityThread.main(ActivityThread.java:7993)
E/flutter (17926): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (17926): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
E/flutter (17926): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955)
E/flutter (17926): )
E/flutter (17926): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
E/flutter (17926): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
E/flutter (17926): <asynchronous suspension>
E/flutter (17926):

**Comment by v7lin** [comment]
2.3.1/2.3.1-iOS-NoPay
