### ISSUE TITLE
ios 正常，android 报错

### ISSUE THREAD

**Issue by abi7321** [rxreader/wechat_kit#79]
> Task :wechat_kit:processVendorReleaseManifest FAILED
F:\Android\flutter\.pub-cache\hosted\pub.flutter-io.cn\wechat_kit-2.3.1\android\src\vendor\AndroidManifest.xml:10:9-50 Error:
	Missing 'package' key attribute on element package at AndroidManifest.xml:10:9-50
F:\Android\flutter\.pub-cache\hosted\pub.flutter-io.cn\wechat_kit-2.3.1\android\src\vendor\AndroidManifest.xml Error:
	Validation failed, exiting

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.

         *********************************************************
WARNING: This version of flutter_webview_plugin will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************

This version of flutter_webview_plugin will break your Android build if it or its dependencies aren't compatible with AndroidX.

Execution failed for task ':wechat_kit:processVendorReleaseManifest'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Manifest merger failed with multiple errors, see logs

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

这行删除可以生成但不能启动，闪退
    <queries>
        
        <package android:name="com.tencent.mm" />
    </queries>

**Comment by v7lin** [comment]
请认真阅读 README.md

```gradle
buildscript {
    dependencies {
        // 3.5.4/3.6.4/4.x.x
        classpath 'com.android.tools.build:gradle:3.5.4'
    }
}
```
