### ISSUE TITLE
flutter版本 2.2.3,参数无法试用，目前wechat_kit，weibo_kit，tencent_kit全有这样的问题。

### ISSUE THREAD

**Issue by situxinxin** [rxreader/wechat_kit#86]
使用快照：
wechat_kit: 
    git:
      url: https://github.com/rxreader/wechat_kit.git 
    git:
      url: https://github.com/rxreader/weibo_kit.git
  tencent_kit:
    git:
      url: https://github.com/rxreader/tencent_kit.git

不能试用参数，参数全部报错；
微信
![image](https://user-images.githubusercontent.com/16554261/126141392-d9cd73e0-75cc-406d-aa0a-210f2957865f.png)
![image](https://user-images.githubusercontent.com/16554261/126141441-c150ff0f-6943-4603-bfb0-c8725ac90b76.png)

QQ
![image](https://user-images.githubusercontent.com/16554261/126141252-2ca1c8ab-f91a-4cbc-b3e6-43310d0fd6d8.png)
微博
![image](https://user-images.githubusercontent.com/16554261/126141320-7bbcbbbe-1e44-4cd1-9fcb-da18cc7752f5.png)

**Comment by v7lin** [comment]
flutter 2.0 & null-safety
