### ISSUE TITLE
git库 调用支付 MissingPluginException

### ISSUE THREAD

**Issue by HealingW** [RxReader/wechat_kit#89]
Flutter version 2.2.1 
Xcode 12.4
iOS 14.4

dependencies:
 wechat_kit:
    git:
      url: https://github.com/rxreader/wechat_kit.git

Unhandled Exception: MissingPluginException(No implementation found for method pay on channel v7lin.github.io/wechat_kit)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
<asynchronous suspension>

**Comment by rongxin1990** [comment]
这个问题解决了吗？为什么我又遇到了一样的问题
